### ISSUE TITLE
Formatação de strings

### ISSUE THREAD

**Issue by ViniPetra** [TheoBortoletto/Python-Exercices#1]
Fala, Theo!

No seu arquivo Entrada e saída de dados - Python/Exercício 001.py, você escreveu:

print("A média destes produtos é: %.2f" %media, ".\n")

Há uma outra forma que eu acho mais fácil de fazer isso e gostaria de compartilhar contigo:

print(f"A média destes produtos é: {media}.\n")

Ao colocar o "f", você pode colocar quantas chaves ({}) quiser e colocar expressões e variáveis dentro dela. O \n também será executado.

Outro exemplo:

a = 1 
b = 2

print(f"A soma é: { a + b}")

Bons estudos!

**Comment by TheoBortoletto** [comment]
Eaii Vini,

Poxa, é bem mais fácil mesmo, dessa maneira o código fica mais "clean".

Valeu brother :).

**Comment by ViniPetra** [comment]
Tmj!
